### ISSUE TITLE
关于章节标题问题

### ISSUE THREAD

**Issue by Nine499** [HammerCloth/BangumiCalendar-python#4]
本服务会把每集动画章节的 “中文标题” 写进日历的备注里。
但是像 天使大人 https://bgm.tv/subject/364822 或者 尼尔 https://bgm.tv/subject/368116 ，
天使大人 没来得及更新中文章节标题 尼尔 根本没有中文章节标题 就会显示为空。
我觉得日历的备注可以同时显示中文与原文标题

**Comment by HammerCloth** [comment]
因为原文标题一般是日文，看不懂， 我就直接去掉了原标题显示，这样日历详情会比较简洁
